version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./seed:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: pathrise

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  express:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - DEBUG=pathrise:*
      - NODE_ENV=development
